-- Animation registry - auto-generated by build.ps1, do not edit manually
-- To add animations: place .blp files in this folder and rebuild
EreaRpAnimationRegistry = {
    lit_candle = {
        texture = "Interface\\AddOns\\erea-rp-common\\blp-videos\\Lit_candle",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    moonstone_compass = {
        texture = "Interface\\AddOns\\erea-rp-common\\blp-videos\\Moonstone_compass",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    sunfire_beacon = {
        texture = "Interface\\AddOns\\erea-rp-common\\blp-videos\\Sunfire_beacon",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
}